version: 2
updates:
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily

  - directory: images/src/alpine-base
    package-ecosystem: docker
    schedule:
      interval: daily

  - directory: images/src/ubuntu-base
    package-ecosystem: docker
    schedule:
      interval: daily

  - directory: images/src/wpvip-base
    package-ecosystem: docker
    schedule:
      interval: daily

  - directory: images/src/ubuntu-base
    package-ecosystem: devcontainers
    schedule:
      interval: daily

  - directory: images/src/wpvip-base
    package-ecosystem: devcontainers
    schedule:
      interval: daily
