#!/bin/sh

set -eu
exec 2>&1

if [ -f /etc/conf.d/mailpit ]; then
    # shellcheck source=/dev/null
    . /etc/conf.d/mailpit
fi

: "${MAILPIT_USER:=nobody}"

exec su-exec "${MAILPIT_USER}:${MAILPIT_USER}" \
    /usr/local/bin/mailpit \
        --listen 127.0.0.1:8025 \
        --smtp 127.0.0.1:1025
