#!/bin/sh

set -eu
exec 2>&1

if [ -f /etc/conf.d/mailhog ]; then
    # shellcheck source=/dev/null
    . /etc/conf.d/mailhog
fi

: "${MAILHOG_USER:=nobody}"

exec su-exec "${MAILHOG_USER}:${MAILHOG_USER}" \
    /usr/local/bin/mailhog \
        -cors-origin \
        -storage memory \
        -api-bind-addr 127.0.0.1:8025 \
        -ui-bind-addr 127.0.0.1:8025 \
        -smtp-bind-addr 127.0.0.1:10025
