name: Build Docker Image

on:
  pull_request:
    branches:
      - trunk
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build image ${{ matrix.image.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - name: Alpine Base
            workspace-folder: images/src/alpine-base
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install @devcontainers/cli
        run: npm install -g @devcontainers/cli

      - name: Build image
        run: |
          devcontainer build \
            --workspace-folder ${{ matrix.image.workspace-folder }} \
            --platform linux/amd64,linux/arm64 \
            --output type=image
