name: Test Features (Global Scenarios)

on:
  push:
    branches:
      - trunk
  pull_request:
  schedule:
    - cron: '15 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  global:
    name: '${{ matrix.test }}'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        test:
          - php82-alpine-base
          - php83-alpine-base
          - php84-alpine-base
          - php82-ubuntu-base
          - php83-ubuntu-base
          - php84-ubuntu-base
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Install @devcontainers/cli
        run: npm install -g @devcontainers/cli

      - name: Expose GitHub Runtime
        uses: Automattic/vip-actions/expose-github-runtime@438cd00aac2463a2dbfb4a747ad7b1ac67a2575a # v0.7.5

      - name: Build images
        run: |
          REPO="$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')"
          IMAGE=
          if [ "${{ contains(matrix.test, 'alpine') }}" = "true" ]; then
            IMAGE=alpine-base
          elif [ "${{ contains(matrix.test, 'ubuntu') }}" = "true" ]; then
            IMAGE=ubuntu-base
          fi
          devcontainer build \
            --workspace-folder "base-images/src/${IMAGE}" \
            --image-name="ghcr.io/${REPO}/${IMAGE}:latest" \
            --cache-from type=gha

      - name: Run tests
        run: devcontainer features test -p features --global-scenarios-only --filter "${{ matrix.test }}"
