name: ShellCheck

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shellcheck:
    name: Lint with shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b

      - name: Add error matcher
        run: echo "::add-matcher::$(pwd)/.github/problem-matcher-gcc.json"

      - name: Run shellcheck
        run: shellcheck -o all -s sh -f gcc $(find . -path ./.git -prune -o -type f -executable -print)
