name: ShellCheck

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shellcheck:
    name: Lint with shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Add error matcher
        run: echo "::add-matcher::$(pwd)/.github/problem-matcher-gcc.json"

      - name: Run shellcheck
        run: shellcheck -o all -s sh -f gcc $(find . -path ./.git -prune -o -type f -executable -print)
