name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: wpcomvip-bot
          password: ${{ secrets.WPCOM_VIP_BOT_TOKEN }}

      - run: cat ~/.docker/config.json || true
