name: Build ubuntu-cross Docker Image

on:
  push:
    branches:
      - trunk
    paths: 
      - '.github/workflows/ubuntu-cross.yml'
      - 'tools/ubuntu-cross/**'
  pull_request:
    paths: 
      - '.github/workflows/ubuntu-cross.yml'
      - 'tools/ubuntu-cross/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build ubuntu-cross
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # v6.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@abd2ef45e78c5afb21d64d4ca52ee8550d9572c7 # v4.5.1
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.base_ref == null }}

      - name: Build and push image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        id: push
        with:
          context: .
          file: ./tools/ubuntu-cross/Dockerfile
          push: ${{ github.base_ref == null }}
          tags: ghcr.io/automattic/vip-codespaces/ubuntu-cross:latest
          cache-from: type=gha,scope=ubuntu-cross
          cache-to: type=gha,mode=max,scope=ubuntu-cross
          no-cache: ${{ github.event_name == 'workflow_dispatch' }}

      - name: Attest provenance
        uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4.2.2
        with:
          subject-name: ghcr.io/automattic/vip-codespaces/ubuntu-cross
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
        if: ${{ github.base_ref == null }}
