name: Build ubuntu-cross Docker Image

on:
  push:
    branches:
      - trunk
    paths: 
      - '.github/workflows/ubuntu-cross.yml'
      - 'tools/ubuntu-cross/**'
  pull_request:
    paths: 
      - '.github/workflows/ubuntu-cross.yml'
      - 'tools/ubuntu-cross/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build ubuntu-cross
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.base_ref == null }}

      - name: Build and push image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        id: push
        with:
          context: .
          file: ./tools/ubuntu-cross/Dockerfile
          push: ${{ github.base_ref == null }}
          tags: ghcr.io/automattic/vip-codespaces/ubuntu-cross:latest
          cache-from: type=gha,scope=ubuntu-cross
          cache-to: type=gha,mode=max,scope=ubuntu-cross
          no-cache: ${{ github.event_name == 'workflow_dispatch' }}

      - name: Attest provenance
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
        with:
          subject-name: ghcr.io/automattic/vip-codespaces/ubuntu-cross
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
        if: ${{ github.base_ref == null }}
