name: Build ubuntu-cross Docker Image

on:
  push:
    branches:
      - trunk
    paths: 
      - '.github/workflows/ubuntu-cross.yml'
      - 'tools/ubuntu-cross/**'
  pull_request:
    paths: 
      - '.github/workflows/ubuntu-cross.yml'
      - 'tools/ubuntu-cross/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build ubuntu-cross
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.base_ref == null }}

      - name: Build and push image
        uses: docker/build-push-action@601a80b39c9405e50806ae38af30926f9d957c47 # v6.19.1
        id: push
        with:
          context: .
          file: ./tools/ubuntu-cross/Dockerfile
          push: ${{ github.base_ref == null }}
          tags: ghcr.io/automattic/vip-codespaces/ubuntu-cross:latest
          cache-from: type=gha,scope=ubuntu-cross
          cache-to: type=gha,mode=max,scope=ubuntu-cross
          no-cache: ${{ github.event_name == 'workflow_dispatch' }}

      - name: Attest provenance
        uses: actions/attest-build-provenance@96278af6caaf10aea03fd8d33a09a777ca52d62f # v3.2.0
        with:
          subject-name: ghcr.io/automattic/vip-codespaces/ubuntu-cross
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
        if: ${{ github.base_ref == null }}
