name: Validate Features

on:
  pull_request:
    paths:
      - "features/src/**/devcontainer-feature.json"
      - ".github/workflows/validate.yml"

permissions:
  contents: read

jobs:
  validate:
    name: Validate devcontainer-feature.json files
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633

      - name: Validate devcontainer-feature.json files
        uses: devcontainers/action@v1.4.2
        with:
          validate-only: "true"
          base-path-to-features: "./features/src"
