name: Validate Features

on:
  pull_request:
    paths:
      - "features/src/**/devcontainer-feature.json"
      - ".github/workflows/validate.yml"

permissions:
  contents: read

jobs:
  validate:
    name: Validate devcontainer-feature.json files
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b

      - name: Validate devcontainer-feature.json files
        uses: devcontainers/action@v1.4.2
        with:
          validate-only: "true"
          base-path-to-features: "./features/src"
